-- Staff Apps
CREATE TABLE IF NOT EXISTS staffapps (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    qualities TEXT NOT NULL,
    future TEXT NOT NULL,
    reference VARCHAR(50) NOT NULL,
    sent_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

-- Developer Apps
CREATE TABLE IF NOT EXISTS devapps (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    qualities TEXT NOT NULL,
    future TEXT NOT NULL,
    reference VARCHAR(50) NOT NULL,
    sent_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)